services:

  springboot:
    build:
      context: app
      dockerfile: $DOCKERFILE
    depends_on:
      - postgres
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_URL: jdbc:postgresql://database_cv24:5432/$POSTGRES_DB
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - .m2:/root/.m2
      - ./app:/app
    stdin_open: true
    tty: true


  postgres:
    image: 'postgres:latest'
    container_name: database_cv24
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - '5432:5432'
