//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.13 at 04:18:45 PM UTC 
//


package fr.univrouen.cv24.entities;

import fr.univrouen.cv24.configuration.DateAdapter;
import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import java.time.LocalDate;


/**
 * <p>Java class for certifType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="certifType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="datedeb" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="datefin" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="titre" type="{http://univ.fr/cv24}string32"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "certifType", propOrder = {
    "datedeb",
    "datefin",
    "titre"
})
@Entity
public class CertifType {

    @Id
    @GeneratedValue
    @XmlTransient
    private Long id;

    @XmlElement(required = true)
    protected String titre;

    @XmlSchemaType(name = "date")
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(DateAdapter.class)
    @Column(name = "datedeb")
    private LocalDate datedeb;

    @XmlSchemaType(name = "date")
    @XmlJavaTypeAdapter(DateAdapter.class)
    @Column(name = "datefin")
    private LocalDate datefin;


    /**
     * Gets the value of the datedeb property.
     * 
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getDatedeb() {
        return datedeb;
    }

    /**
     * Sets the value of the datedeb property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setDatedeb(LocalDate value) {
        this.datedeb = value;
    }

    /**
     * Gets the value of the datefin property.
     *
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getDatefin() {
        return datefin;
    }

    /**
     * Sets the value of the datefin property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setDatefin(LocalDate value) {
        this.datefin = value;
    }

    /**
     * Gets the value of the titre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitre() {
        return titre;
    }

    /**
     * Sets the value of the titre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitre(String value) {
        this.titre = value;
    }

    public Long getId() {
        return id;
    }
}
