//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.13 at 04:18:45 PM UTC 
//


package fr.univrouen.cv24.entities;

import jakarta.persistence.*;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for cv24Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cv24Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{http://univ.fr/cv24}identite"/&gt;
 *         &lt;element ref="{http://univ.fr/cv24}objectif"/&gt;
 *         &lt;element ref="{http://univ.fr/cv24}prof" minOccurs="0"/&gt;
 *         &lt;element ref="{http://univ.fr/cv24}competences"/&gt;
 *         &lt;element ref="{http://univ.fr/cv24}divers" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "cv24")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cv24Type", propOrder = {

})
@Entity
@Table
public class Cv24Type {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @XmlTransient
    private Long id;

    @XmlElement(required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected IdentiteType identite;

    @XmlElement(required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected ObjectifType objectif;

    @OneToOne(cascade = CascadeType.ALL)
    protected ProfType prof;

    @XmlElement(required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected CompetencesType competences;

    @OneToOne(cascade = CascadeType.ALL)
    protected DiversType divers;

    /**
     * Gets the value of the identite property.
     * 
     * @return
     *     possible object is
     *     {@link IdentiteType }
     *     
     */
    public IdentiteType getIdentite() {
        return identite;
    }

    /**
     * Sets the value of the identite property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentiteType }
     *     
     */
    public void setIdentite(IdentiteType value) {
        this.identite = value;
    }

    /**
     * Gets the value of the objectif property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectifType }
     *     
     */
    public ObjectifType getObjectif() {
        return objectif;
    }

    /**
     * Sets the value of the objectif property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectifType }
     *     
     */
    public void setObjectif(ObjectifType value) {
        this.objectif = value;
    }

    /**
     * Gets the value of the prof property.
     * 
     * @return
     *     possible object is
     *     {@link ProfType }
     *     
     */
    public ProfType getProf() {
        return prof;
    }

    /**
     * Sets the value of the prof property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfType }
     *     
     */
    public void setProf(ProfType value) {
        this.prof = value;
    }

    /**
     * Gets the value of the competences property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencesType }
     *     
     */
    public CompetencesType getCompetences() {
        return competences;
    }

    /**
     * Sets the value of the competences property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencesType }
     *     
     */
    public void setCompetences(CompetencesType value) {
        this.competences = value;
    }

    /**
     * Gets the value of the divers property.
     * 
     * @return
     *     possible object is
     *     {@link DiversType }
     *     
     */
    public DiversType getDivers() {
        return divers;
    }

    /**
     * Sets the value of the divers property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiversType }
     *     
     */
    public void setDivers(DiversType value) {
        this.divers = value;
    }

    public Long getId() {
        return id;
    }
}
