//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.13 at 04:18:45 PM UTC 
//


package fr.univrouen.cv24.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for objectifType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objectifType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://univ.fr/cv24&gt;string128"&gt;
 *       &lt;attribute name="statut" use="required" type="{http://univ.fr/cv24}statutType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectifType", propOrder = {
    "value"
})
@Entity
public class ObjectifType {

    @Id
    @GeneratedValue
    @XmlTransient
    private Long id;

    @XmlValue
    protected String value;
    @XmlAttribute(name = "statut", required = true)
    protected StatutType statut;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the statut property.
     * 
     * @return
     *     possible object is
     *     {@link StatutType }
     *     
     */
    public StatutType getStatut() {
        return statut;
    }

    /**
     * Sets the value of the statut property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatutType }
     *     
     */
    public void setStatut(StatutType value) {
        this.statut = value;
    }

    public Long getId() {
        return id;
    }
}
