FROM maven:3.8-openjdk-17-slim

LABEL authors="Etienne Binginot, Axelle Mazuy"

WORKDIR /app

# Install dependencies
COPY pom.xml /app
RUN mvn clean dependency:go-offline
RUN apt install -y watch

# Get project files
COPY . /app

# Run springboot in watch mode
CMD sh ./docker-entrypoint.sh